In [9]:
from rotation import Rotation
import numpy as np

x = np.asarray([[1, 0, 0], [0, 0, 0], [0, 0, 0]])
x


array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
rotated_x = Rotation(alpha= 3/4 * np.pi, beta=0, gamma=0)
rotated_x

matrix([[ 1.        ,  0.        ,  0.        ],
        [ 0.        , -0.70710678, -0.70710678],
        [ 0.        ,  0.70710678, -0.70710678]])

In [34]:
from scipy.spatial.transform import Rotation as R 
rot = R.random(num=1, random_state=42)
rotated_x = rot.apply(x)
rotated_x

array([[0.70807124, 0.61083703, 0.35427846],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [41]:
#np.sqrt(rotated_x[0, ...][0]**2 + rotated_x[0, ...][1]**2 + rotated_x[0, ...][2]**2)

y = np.random.rand(3, 3)
print(y)

rotated_y = rot.apply(y)
print(rotated_y)
print(np.sqrt(rotated_y[0, ...][0]**2 + rotated_y[0, ...][1]**2 + rotated_y[0, ...][2]**2)) 
print(np.sqrt(y[0, ...][0]**2 + y[0, ...][1]**2 + y[0, ...][2]**2))

[[0.5018605  0.900802   0.03193335]
 [0.65462006 0.97916993 0.49654307]
 [0.69064408 0.23544798 0.21582991]]
[[-0.27487882  0.78994424  0.60395171]
 [-0.18738232  0.66524717  1.07526289]
 [ 0.33964488  0.43138132  0.52683874]]
1.0316627075584326
1.0316627075584326
